CUSTCOM-179 PrimeFaces AutoSelect Event is Null within Custom Component
payara/patched-src-el-ri pull request #1
Opened 2020-03-26 23:55 UTC by MeroRai

2020-03-27 09:50 UTC, dmatej commented on api/src/main/java/javax/el/ELUtil.java
> +                    if (ParameterType.getName().equals("javax.faces.event.AjaxBehaviorEvent")) {
I don't like it much, relying on class names is extremely fragile.
Also ... what it does ... 
IF we received null or zero parameters THEN look at the method signature, and IF ANY of those parameters is of exact class name execute the method with what we received.

IN ALL OTHER cases transform parameters to new parameter array and execute the method.

2020-03-27 09:53 UTC, dmatej commented on api/src/main/java/javax/el/ELUtil.java
> +            throw new IllegalArgumentException(iae);
you can rethrow iae directly. But ... to me it looks like it was explicitly desired to throw ELException instead.
I think that in good code this catch block should not be there. But first we need to know why is it here.

2020-04-10 09:28 UTC, dmatej requested changes

2020-04-10 09:28 UTC, dmatej commented on api/src/main/java/javax/el/ELUtil.java
> +            throw new IllegalArgumentException(iae);
I'm reviewing it for second time and I think the ElException is desired here, so it  should be reset back or explained at least.

2020-04-10 09:28 UTC, dmatej commented on impl/src/main/java/com/sun/el/util/ReflectionUtil.java
> +                    if (ParameterType.getName().equals("javax.faces.event.AjaxBehaviorEvent")) {
This is really ugly fragile hack. Bad code, antipattern.

2020-04-10 09:28 UTC, dmatej commented on impl/src/main/java/com/sun/el/util/ReflectionUtil.java
> +            throw new IllegalArgumentException(iae);
Dtto, explain this change and delete catch block XOR leave original ELException here.

2020-04-20 17:05 UTC, MeroRai commented
@dmatej I agree with your review. As I have explained [here](https://github.com/payara/Payara/pull/4592), this issue is caused by PrimeFaces. This is the only way I could find to fix it outside PrimeFaces, as it invokes without an event on its first attempt and only invokes with an event when an exception is thrown.

2020-04-21 16:54 UTC, dmatej approved these changes
1) The fix works with PrimeFaces 5.2 and Primefaces 8.0
2) The bug is in PrimeFaces, so this is only a temporary workaround on our side as it seems it does not break other things.

2020-04-23 08:54 UTC, merged